# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.

# Despawn model if host vex is missing or dead (prevents immortal display entity leaks)
execute unless entity @e[type=vex,tag=stellarity.pixie,distance=..3.5] run return run function stellarity:util/animated_java/pixie/remove/this

# Distance LOD: skip bone animation calculations if no player is nearby
execute unless entity @a[distance=..48] run return 1

execute if entity @s[tag=stellarity.util.animated_java.pixie.animation.idle_pixie.playing] run function stellarity:util/animated_java/pixie/animations/idle_pixie/zzz/on_tick
execute if entity @s[tag=stellarity.util.animated_java.pixie.animation.flying_pixie.playing] run function stellarity:util/animated_java/pixie/animations/flying_pixie/zzz/on_tick
execute on passengers run rotate @s ~ ~
