name: Build Resource Pack
on:
  push:
    branches:
      - master
    paths:
      - 'resource_pack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity-ResourcePack
        path: |
          resource_pack/assets/
          resource_pack/pack.png
          resource_pack/pack.mcmeta
        retention-days: 7
        compression-level: 9
