name: Build Music Addon
on:
  push:
    branches:
      - master
    paths:
      - 'music_pack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity-Music-Addon
        path: |
          music_pack/assets/
          music_pack/pack.png
          music_pack/pack.mcmeta
        retention-days: 7
        compression-level: 9
