name: DEV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: DEV
        path: |
          data/
          pack.mcmeta
